import React, { useEffect, useState } from 'react';
import { useParams, useLocation } from 'react-router-dom';
import api from '../api';
import { Download, Share2, Printer, CheckCircle, ShieldAlert, FileText, Settings, Target } from 'lucide-react';
import CaseOverview from '../components/CaseOverview';
import NetworkGraph from '../components/NetworkGraph';
import Timeline from '../components/Timeline';
import RegulationPanel from '../components/RegulationPanel';
import AISummaryPanel from '../components/AISummaryPanel';
import CaseQnA from '../components/CaseQnA';

const tabs = ['Overview', 'Network Graph', 'Timeline', 'Regulations', 'AI Summary', 'Q&A'];

export default function CaseRoom() {
  const { caseId } = useParams();
  const location = useLocation();
  const [caseData, setCaseData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('Overview');
  const [isSpeaking, setIsSpeaking] = useState(false);

  useEffect(() => {
    if (location.hash) {
      const decodedHash = decodeURIComponent(location.hash.replace('#', ''));
      const tabMatch = tabs.find(t => t.replace(" ", "") === decodedHash.replace(" ", "")); if (tabMatch) { setActiveTab(tabMatch); } else if (tabs.includes(decodedHash)) {
        setActiveTab(decodedHash);
      }
    }
  }, [location.hash]);

  useEffect(() => {
    const fetchCase = async () => {
      try {
        const { data } = await api.get(`/cases/${caseId}`);
        setCaseData(data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchCase();
  }, [caseId]);

  if (loading) return <div className="p-8 text-white">Loading case...</div>;
  if (!caseData) return <div className="p-8 text-white">Case not found.</div>;

  return (
    <div className="flex flex-col h-full bg-[#0a0f18] text-slate-200">
      <div className="flex-none bg-[#0d1421] border-b border-slate-800">
        <div className="px-6 py-5 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="h-12 w-12 rounded-xl bg-indigo-500/10 flex items-center justify-center border border-indigo-500/20">
              <ShieldAlert className="text-indigo-400" size={24} />
            </div>
            <div>
              <div className="flex items-center gap-3">
                <h1 className="text-xl font-semibold text-white">{caseData.case_id}</h1>
                <span className="px-2.5 py-1 rounded-md text-xs font-medium bg-rose-500/10 text-rose-400 border border-rose-500/20">
                  {caseData.fraud_score?.risk_score >= 0.8 ? 'High Risk' : 'Medium Risk'}
                </span>
              </div>
              <p className="text-sm text-slate-400 mt-1">Generated by VigilOS Automata</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button className="p-2 hover:bg-slate-800 rounded-lg text-slate-400 hover:text-white transition-colors">
              <Share2 size={18} />
            </button>
            <button className="p-2 hover:bg-slate-800 rounded-lg text-slate-400 hover:text-white transition-colors">
              <Download size={18} />
            </button>
          </div>
        </div>

        <div className="px-6">
          <div className="flex gap-6 border-b border-slate-800/50">
            {tabs.map(tab => (
              <button
                key={tab}
                className={`py-4 text-sm font-medium relative transition-colors ${activeTab === tab ? "text-white" : "text-slate-400 hover:text-slate-200"}`}
                onClick={() => setActiveTab(tab)}
              >
                {tab}
                {activeTab === tab && (
                  <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-indigo-500" />
                )}
              </button>
            ))}
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-auto bg-[#04080f]">
        <div className="p-6 h-full">
          {activeTab === 'Overview' && <CaseOverview caseData={caseData} setCaseData={setCaseData} />}
          {activeTab === 'Network Graph' && <NetworkGraph data={caseData} />}
          {activeTab === 'Timeline' && <Timeline events={caseData.timeline} />}
          {activeTab === 'Regulations' && <RegulationPanel data={caseData.compliance} />}
          {activeTab === 'AI Summary' && <AISummaryPanel data={caseData.explanation} />}
          {activeTab === 'Q&A' && <CaseQnA caseId={caseData.case_id} />}
        </div>
      </div>
    </div>
  );
}
