"""
VigilOS Suspicious Activity Report (SAR) Generator
Generates institutional-grade PDF investigation dossiers using ReportLab.
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.pdfgen import canvas
from io import BytesIO
from datetime import datetime, timezone
from typing import Dict, Any, List, Optional
import xml.sax.saxutils as saxutils

# ── Color Palette ─────────────────────────────────────────────────────────────
PRIMARY_DARK = HexColor("#0F172A")    # Navy / Slate 900
PRIMARY_BLUE = HexColor("#2563EB")    # Blue 600
ACCENT_BLUE  = HexColor("#3B82F6")    # Blue 500
HEADER_BG    = HexColor("#1E293B")    # Slate 800
SECTION_BG   = HexColor("#F1F5F9")    # Slate 100
BORDER_COLOR = HexColor("#CBD5E1")    # Slate 300
BORDER_LIGHT = HexColor("#E2E8F0")    # Slate 200
TEXT_DARK    = HexColor("#0F172A")    # Slate 900
TEXT_MUTED   = HexColor("#64748B")    # Slate 500
ROW_ALT_BG   = HexColor("#F8FAFC")    # Slate 50

# Alert Badges
HIGH_RED     = HexColor("#DC2626")    # Red 600
HIGH_RED_BG  = HexColor("#FEE2E2")    # Red 100
MED_AMBER    = HexColor("#D97706")    # Amber 600
MED_AMBER_BG = HexColor("#FEF3C7")    # Amber 100
LOW_GREEN    = HexColor("#059669")    # Emerald 600
LOW_GREEN_BG = HexColor("#D1FAE5")    # Emerald 100


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas for dynamic total page count and professional headers/footers."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_decorations(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_decorations(self, page_count: int):
        self.saveState()
        case_id = getattr(self, "_case_id", "SAR")
        
        # Running Header (on pages > 1)
        if self._pageNumber > 1:
            self.setFont("Helvetica-Bold", 8)
            self.setFillColor(HexColor("#475569"))
            self.drawString(36, A4[1] - 25, "VigilOS // Suspicious Activity Report (SAR)")
            self.drawRightString(A4[0] - 36, A4[1] - 25, f"Case: {case_id}")
            self.setStrokeColor(HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(36, A4[1] - 29, A4[0] - 36, A4[1] - 29)

        # Running Footer (on all pages)
        self.setStrokeColor(HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(36, 40, A4[0] - 36, 40)
        
        self.setFont("Helvetica", 8)
        self.setFillColor(HexColor("#64748B"))
        self.drawString(36, 28, "Generated by VigilOS v1.0.0 — Confidential & Regulatory Sensitive")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(A4[0] - 36, 28, page_text)
        self.restoreState()


# ── Formatting Helpers ────────────────────────────────────────────────────────

def _escape(text: Any) -> str:
    """Safely escape text for ReportLab XML/HTML-like Paragraphs."""
    if text is None:
        return "Not available"
    s = str(text)
    return saxutils.escape(s)


def _format_currency(val: Any) -> str:
    """Format numeric values as currency."""
    if val is None:
        return "Not available"
    try:
        f = float(val)
        return f"${f:,.2f}"
    except (ValueError, TypeError):
        return _escape(val)


def _format_datetime(val: Any) -> str:
    """Format ISO timestamp into clean UTC representation."""
    if not val:
        return "Not available"
    try:
        if isinstance(val, str):
            dt = datetime.fromisoformat(val.replace("Z", "+00:00"))
            return dt.strftime("%Y-%m-%d %H:%M:%S UTC")
        elif isinstance(val, datetime):
            return val.strftime("%Y-%m-%d %H:%M:%S UTC")
    except Exception:
        return str(val)
    return str(val)


def _get_risk_colors(level: str):
    """Return text color and background color for a risk level."""
    lvl = (level or "").upper()
    if lvl == "HIGH":
        return HIGH_RED, HIGH_RED_BG
    elif lvl == "MEDIUM":
        return MED_AMBER, MED_AMBER_BG
    elif lvl == "LOW":
        return LOW_GREEN, LOW_GREEN_BG
    return TEXT_MUTED, ROW_ALT_BG


def _get_action_colors(action: str):
    """Return text color and background color for recommendation actions."""
    act = (action or "").upper()
    if act == "BLOCK":
        return HIGH_RED, HIGH_RED_BG
    elif act == "ESCALATE":
        return MED_AMBER, MED_AMBER_BG
    elif act in ("MONITOR", "APPROVE"):
        return LOW_GREEN, LOW_GREEN_BG
    return TEXT_MUTED, ROW_ALT_BG


# ── Report Styles Setup ───────────────────────────────────────────────────────

def _get_report_styles():
    """Create custom typography and paragraph styles."""
    styles = getSampleStyleSheet()
    
    # Base Body Style
    styles.add(ParagraphStyle(
        name="ReportBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11.5,
        textColor=TEXT_DARK
    ))

    styles.add(ParagraphStyle(
        name="ReportBodyBold",
        parent=styles["ReportBody"],
        fontName="Helvetica-Bold",
    ))

    styles.add(ParagraphStyle(
        name="ReportBodyMuted",
        parent=styles["ReportBody"],
        textColor=TEXT_MUTED,
        fontSize=8,
        leading=10.5
    ))

    styles.add(ParagraphStyle(
        name="ReportBodyJustify",
        parent=styles["ReportBody"],
        alignment=TA_JUSTIFY
    ))

    styles.add(ParagraphStyle(
        name="SectionTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9.5,
        leading=12,
        textColor=PRIMARY_DARK
    ))

    styles.add(ParagraphStyle(
        name="TableHeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=10,
        textColor=HexColor("#334155")
    ))

    styles.add(ParagraphStyle(
        name="TableCell",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=10.5,
        textColor=TEXT_DARK
    ))

    styles.add(ParagraphStyle(
        name="TableCellBold",
        parent=styles["TableCell"],
        fontName="Helvetica-Bold"
    ))

    styles.add(ParagraphStyle(
        name="BannerTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=18,
        textColor=HexColor("#FFFFFF")
    ))

    styles.add(ParagraphStyle(
        name="BannerSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=10,
        textColor=HexColor("#94A3B8")
    ))

    styles.add(ParagraphStyle(
        name="BannerRight",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        alignment=TA_RIGHT,
        textColor=HexColor("#CBD5E1")
    ))

    styles.add(ParagraphStyle(
        name="CalloutText",
        parent=styles["ReportBody"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=HexColor("#1E293B")
    ))

    return styles


def _create_section_heading(title: str, styles: Any) -> Table:
    """Generate a clean section heading with an accent color left bar."""
    t = Table(
        [[Paragraph(f"<b>{_escape(title.upper())}</b>", styles["SectionTitle"])]],
        colWidths=[523]
    )
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), SECTION_BG),
        ('LINELEFT', (0, 0), (0, 0), 3.5, PRIMARY_BLUE),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    return t


# ── Report Generator Implementation ───────────────────────────────────────────

def generate_report(case: dict) -> bytes:
    """
    Generate a complete, professional Suspicious Activity Report (SAR) PDF
    from a VigilOS case dictionary.
    
    Args:
        case: Dictionary containing case investigation data.
        
    Returns:
        bytes: The compiled PDF document binary.
    """
    buffer = BytesIO()
    
    # Document Setup (A4 size: 595.27 x 841.89 pt, margins: 36pt = 0.5 in, usable width: 523.27 pt)
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=48
    )
    
    case_id = str(case.get("case_id", "CASE-UNKNOWN"))
    
    class CaseNumberedCanvas(NumberedCanvas):
        _case_id = case_id
        
    styles = _get_report_styles()
    story = []

    # ── 1. HEADER BANNER ──────────────────────────────────────────────────────
    gen_time = _format_datetime(datetime.now(timezone.utc).isoformat())
    header_left = Paragraph(
        f'<font size="7.5" color="#93C5FD"><b>VIGILOS FRAUD INVESTIGATION SYSTEM</b></font><br/>'
        f'<font size="14" color="#FFFFFF"><b>SUSPICIOUS ACTIVITY REPORT</b></font><br/>'
        f'<font size="7.5" color="#94A3B8">Financial Crime Intelligence &amp; Autonomous Dossier</font>',
        styles["BannerSubtitle"]
    )
    header_right = Paragraph(
        f'<font size="10" color="#FFFFFF"><b>CASE: {_escape(case_id)}</b></font><br/>'
        f'<font size="7.5" color="#CBD5E1">Generated: {_escape(gen_time)}</font><br/>'
        f'<font size="7.5" color="#FCA5A5"><b>CONFIDENTIAL // LAW ENFORCEMENT SENSITIVE</b></font>',
        styles["BannerRight"]
    )

    header_table = Table([[header_left, header_right]], colWidths=[310, 213])
    header_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), PRIMARY_DARK),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 8))

    # ── 2. CASE OVERVIEW ──────────────────────────────────────────────────────
    story.append(_create_section_heading("1. Case Overview", styles))
    story.append(Spacer(1, 4))

    status = (case.get("status") or "pending").upper()
    created_at = _format_datetime(case.get("created_at"))
    
    fraud_score_data = case.get("fraud_score") or {}
    risk_score = fraud_score_data.get("risk_score")
    risk_level = (fraud_score_data.get("risk_level") or "UNKNOWN").upper()
    risk_text_color, risk_bg_color = _get_risk_colors(risk_level)

    recom_data = case.get("recommendation") or {}
    recom_action = (recom_data.get("action") or "MONITOR").upper()
    recom_conf = recom_data.get("confidence")
    recom_str = f"{recom_action}" + (f" ({recom_conf*100:.0f}%)" if recom_conf is not None else "")
    recom_color, recom_bg_color = _get_action_colors(recom_action)

    risk_score_display = f"{risk_score:.3f} ({risk_score*100:.1f}%)" if isinstance(risk_score, (int, float)) else "Not available"
    
    human_dec = case.get("human_decision")
    decision_badge = human_dec.upper() if human_dec else "PENDING REVIEW"
    dec_color, _ = _get_action_colors(decision_badge if human_dec else "PENDING")

    overview_matrix = [
        [
            Paragraph("<b>Case Reference:</b>", styles["TableCellBold"]),
            Paragraph(_escape(case_id), styles["TableCell"]),
            Paragraph("<b>Investigation Status:</b>", styles["TableCellBold"]),
            Paragraph(f"<b>{_escape(status)}</b>", styles["TableCell"])
        ],
        [
            Paragraph("<b>Created Timestamp:</b>", styles["TableCellBold"]),
            Paragraph(_escape(created_at), styles["TableCell"]),
            Paragraph("<b>Overall Risk Level:</b>", styles["TableCellBold"]),
            Paragraph(f'<font color="{risk_text_color.hexval()}"><b>{_escape(risk_level)}</b></font>', styles["TableCell"])
        ],
        [
            Paragraph("<b>Calculated Risk Score:</b>", styles["TableCellBold"]),
            Paragraph(f"<b>{risk_score_display}</b>", styles["TableCell"]),
            Paragraph("<b>Recommended Action:</b>", styles["TableCellBold"]),
            Paragraph(f'<font color="{recom_color.hexval()}"><b>{_escape(recom_str)}</b></font>', styles["TableCell"])
        ],
        [
            Paragraph("<b>Model Version:</b>", styles["TableCellBold"]),
            Paragraph(_escape(fraud_score_data.get("model_version", "1.0")), styles["TableCell"]),
            Paragraph("<b>Human Adjudication:</b>", styles["TableCellBold"]),
            Paragraph(f'<font color="{dec_color.hexval()}"><b>{_escape(decision_badge)}</b></font>', styles["TableCell"])
        ]
    ]

    overview_table = Table(overview_matrix, colWidths=[110, 151, 115, 147])
    overview_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), HexColor("#FFFFFF")),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
        ('BACKGROUND', (0, 0), (0, -1), ROW_ALT_BG),
        ('BACKGROUND', (2, 0), (2, -1), ROW_ALT_BG),
        ('TOPPADDING', (0, 0), (-1, -1), 3.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3.5),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(overview_table)
    story.append(Spacer(1, 8))

    # ── 3. TRANSACTION DETAILS ────────────────────────────────────────────────
    story.append(_create_section_heading("2. Transaction Details", styles))
    story.append(Spacer(1, 4))

    txn = case.get("transaction") or {}
    txn_type = txn.get("type", "TRANSFER")
    txn_amount = txn.get("amount")
    name_orig = txn.get("nameOrig", "Not available")
    name_dest = txn.get("nameDest", "Not available")
    old_orig = txn.get("oldbalanceOrg")
    new_orig = txn.get("newbalanceOrig")
    old_dest = txn.get("oldbalanceDest")
    new_dest = txn.get("newbalanceDest")
    step_val = txn.get("step")
    is_flagged = txn.get("isFlaggedFraud")

    orig_delta_str = "Not available"
    if old_orig is not None and new_orig is not None:
        try:
            delta_orig = float(new_orig) - float(old_orig)
            pct_drain = (abs(delta_orig) / (float(old_orig) + 1e-6)) * 100 if float(old_orig) > 0 else 0.0
            orig_delta_str = f"{_format_currency(delta_orig)} ({pct_drain:.1f}% drain)"
        except Exception:
            orig_delta_str = "Not available"

    dest_delta_str = "Not available"
    if old_dest is not None and new_dest is not None:
        try:
            delta_dest = float(new_dest) - float(old_dest)
            if float(old_dest) == 0.0 and float(new_dest) == 0.0:
                dest_delta_str = "$0.00 (Zero-Balance Mule Pattern)"
            else:
                dest_delta_str = f"+{_format_currency(delta_dest)}"
        except Exception:
            dest_delta_str = "Not available"

    flag_str = "Yes" if is_flagged == 1 else "No"
    try:
        step_str = f"Step {step_val} (Hour {int(step_val) % 24})" if step_val is not None else "Not specified"
    except Exception:
        step_str = str(step_val)

    txn_matrix = [
        [
            Paragraph("<b>Transaction Type:</b>", styles["TableCellBold"]),
            Paragraph(f"<b>{_escape(txn_type)}</b>", styles["TableCell"]),
            Paragraph("<b>Transaction Amount:</b>", styles["TableCellBold"]),
            Paragraph(f'<font size="9"><b>{_format_currency(txn_amount)}</b></font>', styles["TableCell"])
        ],
        [
            Paragraph("<b>Sender Account (Origin):</b>", styles["TableCellBold"]),
            Paragraph(f'<font color="#1D4ED8"><b>{_escape(name_orig)}</b></font>', styles["TableCell"]),
            Paragraph("<b>Receiver Account (Dest):</b>", styles["TableCellBold"]),
            Paragraph(f'<font color="#B91C1C"><b>{_escape(name_dest)}</b></font>', styles["TableCell"])
        ],
        [
            Paragraph("<b>Sender Prior Balance:</b>", styles["TableCellBold"]),
            Paragraph(_format_currency(old_orig), styles["TableCell"]),
            Paragraph("<b>Receiver Prior Balance:</b>", styles["TableCellBold"]),
            Paragraph(_format_currency(old_dest), styles["TableCell"])
        ],
        [
            Paragraph("<b>Sender New Balance:</b>", styles["TableCellBold"]),
            Paragraph(_format_currency(new_orig), styles["TableCell"]),
            Paragraph("<b>Receiver New Balance:</b>", styles["TableCellBold"]),
            Paragraph(_format_currency(new_dest), styles["TableCell"])
        ],
        [
            Paragraph("<b>Sender Balance Delta:</b>", styles["TableCellBold"]),
            Paragraph(_escape(orig_delta_str), styles["TableCell"]),
            Paragraph("<b>Receiver Balance Delta:</b>", styles["TableCellBold"]),
            Paragraph(_escape(dest_delta_str), styles["TableCell"])
        ],
        [
            Paragraph("<b>Simulation / Step Hour:</b>", styles["TableCellBold"]),
            Paragraph(_escape(step_str), styles["TableCell"]),
            Paragraph("<b>System Flagged Rule:</b>", styles["TableCellBold"]),
            Paragraph(_escape(flag_str), styles["TableCell"])
        ]
    ]

    txn_table = Table(txn_matrix, colWidths=[115, 146, 115, 147])
    txn_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), HexColor("#FFFFFF")),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
        ('BACKGROUND', (0, 0), (0, -1), ROW_ALT_BG),
        ('BACKGROUND', (2, 0), (2, -1), ROW_ALT_BG),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(txn_table)
    story.append(Spacer(1, 8))

    # ── 3. RISK ANALYSIS & ML SIGNALS ─────────────────────────────────────────
    story.append(_create_section_heading("3. Risk Analysis & ML Signals", styles))
    story.append(Spacer(1, 4))

    score_val = fraud_score_data.get("risk_score", 0.0)
    score_pct_str = f"{score_val*100:.1f}%" if isinstance(score_val, (int, float)) else "0.0%"
    model_ver = fraud_score_data.get("model_version", "1.0")

    gauge_desc = (
        f"The <b>XGBoost ML Fraud Classifier (Model v{_escape(model_ver)})</b> evaluated this transaction "
        f"with a fraud probability score of <b>{score_pct_str}</b>, classifying it into the "
        f"<b><font color=\"{risk_text_color.hexval()}\">{_escape(risk_level)}</font></b> risk band. "
        f"Six behavioral, structural, and relational fraud signals were computed to assess anomaly severity:"
    )
    story.append(Paragraph(gauge_desc, styles["ReportBody"]))
    story.append(Spacer(1, 4))

    signals_fired = fraud_score_data.get("signals_fired") or {}

    def _assess_type(v):
        try:
            return "Triggered (High Risk)" if v is not None and float(v) > 0.5 else "Normal"
        except Exception:
            return "Evaluated"

    def _assess_ratio(v):
        try:
            if v is None: return "Normal"
            f = float(v)
            return f"High Drain ({f*100:.1f}%)" if f > 0.5 else f"Normal ({f*100:.1f}%)"
        except Exception:
            return "Evaluated"

    def _assess_mismatch(v):
        try:
            if v is None: return "Consistent"
            f = float(v)
            return f"Mismatch ({_format_currency(f)})" if abs(f) > 0.01 else "Consistent (0.00)"
        except Exception:
            return "Evaluated"

    def _assess_mule(v):
        try:
            return "Mule Signature Detected" if v is not None and float(v) > 0.5 else "Normal"
        except Exception:
            return "Evaluated"

    def _assess_timing(v):
        try:
            return f"Hour {int(float(v))}" if v is not None else "Normal"
        except Exception:
            return "Evaluated"

    def _assess_velocity(v):
        try:
            return f"Velocity: {_format_currency(v)}" if v is not None else "Standard"
        except Exception:
            return "Evaluated"

    signal_defs = [
        ("type_eligible", "Transaction Type Eligibility", "High-risk flow type (TRANSFER or CASH_OUT)", _assess_type),
        ("amount_balance_ratio", "Amount to Balance Ratio", "Ratio of transferred amount to sender's prior balance", _assess_ratio),
        ("balance_mismatch", "Balance Discrepancy", "Discrepancy between balance delta and transaction amount", _assess_mismatch),
        ("mule_pattern", "Zero-Balance Mule Signature", "Receiver starts and ends transaction with zero balance", _assess_mule),
        ("timing_gap", "Diurnal Timing Factor", "Transaction timing interval (step modulo 24 hours)", _assess_timing),
        ("velocity", "Volume Velocity Index", "Normalized velocity ratio (amount / step interval)", _assess_velocity)
    ]

    signals_rows = [
        [
            Paragraph("<b>Signal Name</b>", styles["TableHeader"]),
            Paragraph("<b>Raw Value</b>", styles["TableHeader"]),
            Paragraph("<b>Signal Description</b>", styles["TableHeader"]),
            Paragraph("<b>Assessment Status</b>", styles["TableHeader"])
        ]
    ]

    for sig_key, sig_name, sig_desc, assess_fn in signal_defs:
        raw_val = signals_fired.get(sig_key)
        try:
            raw_display = f"{float(raw_val):.4f}" if isinstance(raw_val, (int, float)) else ("Not available" if raw_val is None else str(raw_val))
        except Exception:
            raw_display = str(raw_val)
            
        assessment = assess_fn(raw_val)
        is_alert = "Triggered" in assessment or "Mule" in assessment or "High Drain" in assessment or "Mismatch" in assessment
        assess_color = HIGH_RED.hexval() if is_alert else TEXT_DARK.hexval()
        
        signals_rows.append([
            Paragraph(f"<b>{_escape(sig_name)}</b>", styles["TableCell"]),
            Paragraph(_escape(raw_display), styles["TableCell"]),
            Paragraph(_escape(sig_desc), styles["TableCell"]),
            Paragraph(f'<font color="{assess_color}"><b>{_escape(assessment)}</b></font>', styles["TableCell"])
        ])

    for extra_key, extra_val in signals_fired.items():
        if extra_key not in [s[0] for s in signal_defs]:
            try:
                extra_raw = f"{float(extra_val):.4f}" if isinstance(extra_val, (int, float)) else str(extra_val)
            except Exception:
                extra_raw = str(extra_val)
            signals_rows.append([
                Paragraph(f"<b>{_escape(extra_key)}</b>", styles["TableCell"]),
                Paragraph(_escape(extra_raw), styles["TableCell"]),
                Paragraph("Custom computed feature signal", styles["TableCell"]),
                Paragraph("Evaluated", styles["TableCell"])
            ])

    signals_table = Table(signals_rows, colWidths=[125, 65, 215, 118])
    signals_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), SECTION_BG),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(signals_table)
    story.append(Spacer(1, 8))

    # ── 4. NETWORK & MONEY FLOW ANALYSIS ──────────────────────────────────────
    story.append(_create_section_heading("4. Network & Money Flow Analysis", styles))
    story.append(Spacer(1, 4))

    ring_data = case.get("ring_detection") or {}
    ring_count = ring_data.get("ring_count", 0)
    max_ring_size = ring_data.get("max_ring_size", 0)
    accounts_involved = ring_data.get("accounts_involved") or []
    accounts_str = ", ".join([str(x) for x in accounts_involved]) if accounts_involved else "None detected (No cyclic patterns found)"

    flow_data = case.get("money_flow") or {}
    total_traced = flow_data.get("total_traced", 0.0)
    trace_pct = flow_data.get("trace_percentage", 0.0)
    time_to_cashout = flow_data.get("time_to_cashout") or "N/A"
    paths = flow_data.get("paths") or []

    network_matrix = [
        [
            Paragraph("<b>Cyclic Rings Detected:</b>", styles["TableCellBold"]),
            Paragraph(f'<font color="{(HIGH_RED.hexval() if ring_count > 0 else TEXT_DARK.hexval())}"><b>{ring_count} ring(s) identified</b></font>', styles["TableCell"]),
            Paragraph("<b>Max Ring Node Size:</b>", styles["TableCellBold"]),
            Paragraph(f"{max_ring_size} accounts", styles["TableCell"])
        ],
        [
            Paragraph("<b>Total Volume Traced:</b>", styles["TableCellBold"]),
            Paragraph(f"<b>{_format_currency(total_traced)}</b>", styles["TableCell"]),
            Paragraph("<b>Time to Cashout:</b>", styles["TableCellBold"]),
            Paragraph(_escape(time_to_cashout), styles["TableCell"])
        ],
        [
            Paragraph("<b>Accounts in Rings:</b>", styles["TableCellBold"]),
            Paragraph(_escape(accounts_str), styles["TableCell"]),
            Paragraph("<b>Trace Completeness:</b>", styles["TableCellBold"]),
            Paragraph(f"{float(trace_pct)*100:.1f}% of flow" if isinstance(trace_pct, (int, float)) and float(trace_pct) > 0 else "Direct path", styles["TableCell"])
        ]
    ]

    net_table = Table(network_matrix, colWidths=[115, 146, 115, 147])
    net_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), HexColor("#FFFFFF")),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
        ('BACKGROUND', (0, 0), (0, -1), ROW_ALT_BG),
        ('BACKGROUND', (2, 0), (2, -1), ROW_ALT_BG),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(net_table)

    # If money flow paths exist, show hop table
    if paths and isinstance(paths, list):
        flat_hops = []
        for p in paths:
            if isinstance(p, list):
                flat_hops.extend(p)
            elif isinstance(p, dict):
                flat_hops.append(p)
        
        if flat_hops:
            story.append(Spacer(1, 4))
            flow_rows = [
                [
                    Paragraph("<b>Hop #</b>", styles["TableHeader"]),
                    Paragraph("<b>From Account</b>", styles["TableHeader"]),
                    Paragraph("<b>To Account</b>", styles["TableHeader"]),
                    Paragraph("<b>Type</b>", styles["TableHeader"]),
                    Paragraph("<b>Amount</b>", styles["TableHeader"])
                ]
            ]
            for idx, hop in enumerate(flat_hops[:8], start=1):
                from_acc = hop.get("from") or hop.get("start") or "N/A"
                to_acc = hop.get("to") or hop.get("end") or "N/A"
                hop_type = hop.get("type", "TRANSFER")
                hop_amt = hop.get("amount", 0.0)
                flow_rows.append([
                    Paragraph(f"Hop {idx}", styles["TableCell"]),
                    Paragraph(_escape(from_acc), styles["TableCell"]),
                    Paragraph(_escape(to_acc), styles["TableCell"]),
                    Paragraph(_escape(hop_type), styles["TableCell"]),
                    Paragraph(_format_currency(hop_amt), styles["TableCell"])
                ])
            
            flow_table = Table(flow_rows, colWidths=[45, 130, 130, 85, 133])
            flow_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), SECTION_BG),
                ('GRID', (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
                ('TOPPADDING', (0, 0), (-1, -1), 2.5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 2.5),
                ('LEFTPADDING', (0, 0), (-1, -1), 5),
                ('RIGHTPADDING', (0, 0), (-1, -1), 5),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            story.append(flow_table)

    story.append(Spacer(1, 8))

    # ── 5. COMPLIANCE & REGULATORY REVIEW ─────────────────────────────────────
    story.append(_create_section_heading("5. Compliance & Regulatory Review", styles))
    story.append(Spacer(1, 4))

    compliance_data = case.get("compliance") or {}
    low_confidence = compliance_data.get("low_confidence", False)
    matches = compliance_data.get("matches") or []

    if low_confidence:
        comp_flag_msg = (
            f'<font color="{HIGH_RED.hexval()}"><b>LOW CONFIDENCE MATCH ALERT:</b></font> '
            f'Vector retrieval similarity scored below the established threshold. '
            f'Mandatory manual regulatory review is required by the compliance officer.'
        )
    else:
        comp_flag_msg = (
            f'<font color="{LOW_GREEN.hexval()}"><b>VERIFIED COMPLIANCE MAPPING:</b></font> '
            f'High-confidence semantic matches identified with relevant BSA/AML, FinCEN, and regulatory statutes.'
        )
    story.append(Paragraph(comp_flag_msg, styles["ReportBody"]))
    story.append(Spacer(1, 4))

    if matches and isinstance(matches, list):
        for idx, match in enumerate(matches[:5], start=1):
            reg = match.get("regulation", "Unknown Regulation")
            sec = match.get("section", "N/A")
            sev = (match.get("severity") or "Medium").upper()
            rel = match.get("relevance_score", 0.0)
            cit = match.get("citation_summary") or match.get("text") or "No citation summary available."
            sev_color, _ = _get_risk_colors(sev)
            rel_str = f"{float(rel)*100:.1f}%" if isinstance(rel, (int, float)) else str(rel)

            match_box = [
                [
                    Paragraph(
                        f'<b>{idx}. {_escape(reg)} — Section {_escape(sec)}</b> '
                        f'| Severity: <font color="{sev_color.hexval()}"><b>{_escape(sev)}</b></font> '
                        f'| Relevance: <b>{rel_str}</b>',
                        styles["TableHeader"]
                    )
                ],
                [
                    Paragraph(f"<b>Citation &amp; Relevance Summary:</b> {_escape(cit)}", styles["TableCell"])
                ]
            ]
            match_table = Table(match_box, colWidths=[523])
            match_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, 0), SECTION_BG),
                ('BACKGROUND', (0, 1), (0, 1), HexColor("#FFFFFF")),
                ('BOX', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ('LINEBELOW', (0, 0), (0, 0), 0.5, BORDER_LIGHT),
                ('TOPPADDING', (0, 0), (-1, -1), 3),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ]))
            story.append(match_table)
            story.append(Spacer(1, 4))
    else:
        story.append(Paragraph("<i>No specific regulatory infractions mapped for this transaction pattern.</i>", styles["ReportBodyMuted"]))

    story.append(Spacer(1, 6))

    # ── 6. INVESTIGATION TIMELINE ─────────────────────────────────────────────
    story.append(_create_section_heading("6. Investigation Timeline", styles))
    story.append(Spacer(1, 4))

    timeline_events = case.get("timeline") or []
    if timeline_events and isinstance(timeline_events, list):
        time_rows = [
            [
                Paragraph("<b>Timestamp / Phase</b>", styles["TableHeader"]),
                Paragraph("<b>Event Type</b>", styles["TableHeader"]),
                Paragraph("<b>Source Agent</b>", styles["TableHeader"]),
                Paragraph("<b>Event Description</b>", styles["TableHeader"])
            ]
        ]
        for evt in timeline_events:
            ts = _format_datetime(evt.get("timestamp")) if evt.get("timestamp") != "unknown" else "Phase 1 Execution"
            etype = (evt.get("event_type") or "system").upper()
            src = evt.get("source_agent") or "orchestrator"
            title = evt.get("title", "")
            desc = evt.get("description", "")
            full_desc = f"<b>{_escape(title)}</b>: {_escape(desc)}" if title else _escape(desc)

            time_rows.append([
                Paragraph(_escape(ts), styles["TableCell"]),
                Paragraph(f"<b>{_escape(etype)}</b>", styles["TableCell"]),
                Paragraph(_escape(src), styles["TableCell"]),
                Paragraph(full_desc, styles["TableCell"])
            ])

        timeline_table = Table(time_rows, colWidths=[105, 75, 95, 248])
        timeline_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), SECTION_BG),
            ('GRID', (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('LEFTPADDING', (0, 0), (-1, -1), 5),
            ('RIGHTPADDING', (0, 0), (-1, -1), 5),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        story.append(timeline_table)
    else:
        story.append(Paragraph("<i>No historical timeline events recorded for this case.</i>", styles["ReportBodyMuted"]))

    story.append(Spacer(1, 8))

    # ── 7. AI ANALYSIS & RISK NARRATIVE ───────────────────────────────────────
    story.append(_create_section_heading("7. AI Analysis & Intelligence Summary", styles))
    story.append(Spacer(1, 4))

    explanation_data = case.get("explanation") or {}
    exec_summary = explanation_data.get("summary") or "Executive summary not available."
    key_findings = explanation_data.get("key_findings") or []
    risk_narrative = explanation_data.get("risk_narrative") or "Detailed risk narrative not generated."

    # Executive Summary Card
    summary_cell = [
        Paragraph("<b>EXECUTIVE SUMMARY</b>", styles["TableHeader"]),
        Spacer(1, 2),
        Paragraph(_escape(exec_summary), styles["CalloutText"])
    ]
    summary_table = Table([[summary_cell]], colWidths=[523])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, 0), ROW_ALT_BG),
        ('BOX', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 6))

    # Key Findings Bullets
    if key_findings and isinstance(key_findings, list):
        story.append(Paragraph("<b>Key Investigative Findings:</b>", styles["ReportBodyBold"]))
        story.append(Spacer(1, 2))
        for finding in key_findings:
            bullet_p = Paragraph(f"• {_escape(str(finding))}", styles["ReportBody"])
            story.append(bullet_p)
            story.append(Spacer(1, 2))
        story.append(Spacer(1, 4))

    # Risk Narrative
    if risk_narrative:
        story.append(Paragraph("<b>Detailed Risk Narrative:</b>", styles["ReportBodyBold"]))
        story.append(Spacer(1, 2))
        story.append(Paragraph(_escape(risk_narrative), styles["ReportBodyJustify"]))
        story.append(Spacer(1, 6))

    # Additional Intel: Messages, Links, Correlations (if available)
    msg_data = case.get("message_analysis")
    link_data = case.get("link_analysis")
    corr_data = case.get("correlation")

    if msg_data or link_data or corr_data:
        intel_rows = []
        if msg_data:
            flags = msg_data.get("flags") or []
            flags_str = f"{len(flags)} suspicious flag(s) identified" if flags else "Clean"
            intel_rows.append([
                Paragraph("<b>Message / Phishing Intel:</b>", styles["TableCellBold"]),
                Paragraph(_escape(flags_str), styles["TableCell"])
            ])
        if link_data:
            domain = link_data.get("domain", "N/A")
            is_susp = link_data.get("is_suspicious", False)
            susp_str = "Suspicious Lookalike" if is_susp else "Clean"
            intel_rows.append([
                Paragraph("<b>Link / Infrastructure Intel:</b>", styles["TableCellBold"]),
                Paragraph(f"Domain: {_escape(domain)} ({_escape(susp_str)})", styles["TableCell"])
            ])
        if corr_data:
            corr_cases = corr_data.get("correlated_cases") or []
            shared_accs = corr_data.get("shared_accounts") or []
            corr_str = f"{len(corr_cases)} linked case(s) ({', '.join([str(x) for x in corr_cases[:3]])}) | Shared accounts: {len(shared_accs)}"
            intel_rows.append([
                Paragraph("<b>Cross-Case Correlation:</b>", styles["TableCellBold"]),
                Paragraph(_escape(corr_str), styles["TableCell"])
            ])

        if intel_rows:
            intel_table = Table(intel_rows, colWidths=[150, 373])
            intel_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), HexColor("#FFFFFF")),
                ('GRID', (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
                ('BACKGROUND', (0, 0), (0, -1), ROW_ALT_BG),
                ('TOPPADDING', (0, 0), (-1, -1), 3),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ]))
            story.append(intel_table)
            story.append(Spacer(1, 6))

    story.append(Spacer(1, 4))

    # ── 8. RECOMMENDATION & DECISION FRAMEWORK ─────────────────────────────────
    story.append(_create_section_heading("8. Automated Recommendation", styles))
    story.append(Spacer(1, 4))

    recom_reasoning = recom_data.get("reasoning") or "Standard policy rules applied."
    recom_thresholds = recom_data.get("thresholds_used") or {}
    thresh_str = " | ".join([f"{k.replace('_', ' ').capitalize()}: {v}" for k, v in recom_thresholds.items()]) if recom_thresholds else "Standard production thresholds applied."
    recom_conf_str = f"{recom_conf*100:.1f}%" if isinstance(recom_conf, (int, float)) else "N/A"

    recom_card = [
        [
            Paragraph(
                f'<font size="12" color="{recom_color.hexval()}"><b>ACTION: {_escape(recom_action)}</b></font><br/>'
                f'<font size="8" color="#64748B">Confidence: <b>{recom_conf_str}</b></font>',
                styles["TableCell"]
            ),
            Paragraph(
                f"<b>Decision Logic:</b> {_escape(recom_reasoning)}<br/>"
                f'<font size="7.5" color="#64748B"><b>Thresholds Applied:</b> {_escape(thresh_str)}</font>',
                styles["TableCell"]
            )
        ]
    ]
    recom_table = Table(recom_card, colWidths=[140, 383])
    recom_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, 0), recom_bg_color),
        ('BACKGROUND', (1, 0), (1, 0), HexColor("#FFFFFF")),
        ('BOX', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ('LINEBEFORE', (1, 0), (1, 0), 0.5, BORDER_LIGHT),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(recom_table)
    story.append(Spacer(1, 8))

    # ── 9. HUMAN COMPLIANCE DECISION ─────────────────────────────────────────
    story.append(_create_section_heading("9. Human Compliance Adjudication", styles))
    story.append(Spacer(1, 4))

    decided_by = case.get("decided_by")
    decided_at = _format_datetime(case.get("decided_at"))
    decision_notes = case.get("decision_notes") or "No adjudication notes provided."

    if human_dec:
        decision_matrix = [
            [
                Paragraph("<b>Final Human Decision:</b>", styles["TableCellBold"]),
                Paragraph(f'<font color="{dec_color.hexval()}"><b>{_escape(human_dec.upper())}</b></font>', styles["TableCell"]),
                Paragraph("<b>Adjudicated By:</b>", styles["TableCellBold"]),
                Paragraph(f"<b>{_escape(decided_by or 'Officer')}</b>", styles["TableCell"])
            ],
            [
                Paragraph("<b>Decision Timestamp:</b>", styles["TableCellBold"]),
                Paragraph(_escape(decided_at), styles["TableCell"]),
                Paragraph("<b>Adjudication Status:</b>", styles["TableCellBold"]),
                Paragraph("<b>CASE CLOSED / ADJUDICATED</b>", styles["TableCell"])
            ],
            [
                Paragraph("<b>Officer Compliance Notes:</b>", styles["TableCellBold"]),
                Paragraph(_escape(decision_notes), styles["TableCell"]),
                Paragraph("", styles["TableCell"]),
                Paragraph("", styles["TableCell"])
            ]
        ]
        decision_table = Table(decision_matrix, colWidths=[120, 141, 115, 147])
        decision_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), HexColor("#FFFFFF")),
            ('GRID', (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
            ('BACKGROUND', (0, 0), (0, -1), ROW_ALT_BG),
            ('BACKGROUND', (2, 0), (2, 1), ROW_ALT_BG),
            ('SPAN', (1, 2), (3, 2)),
            ('TOPPADDING', (0, 0), (-1, -1), 3.5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3.5),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        story.append(decision_table)
    else:
        pending_box = [
            [
                Paragraph(
                    '<b>STATUS: PENDING ADJUDICATION</b><br/>'
                    '<font color="#64748B">This case has not yet been adjudicated by a human compliance officer. '
                    'Awaiting final human-in-the-loop review and disposition.</font>',
                    styles["TableCell"]
                )
            ]
        ]
        pending_table = Table(pending_box, colWidths=[523])
        pending_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, 0), ROW_ALT_BG),
            ('BOX', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(pending_table)

    # ── BUILD DOCUMENT ────────────────────────────────────────────────────────
    doc.build(story, canvasmaker=CaseNumberedCanvas)
    return buffer.getvalue()
