import json
from langchain_groq import ChatGroq
import os
from langchain_core.messages import HumanMessage

def recommend(risk_score: float, ring_count: int, compliance_matches: int, signals: dict) -> dict:
    prompt = f"""
You are an expert fraud compliance AI.
Based on the following case metrics, make a definitive recommendation action.

Risk Score: {risk_score} (0.0 to 1.0)
Ring Count (Money Mules): {ring_count}
Compliance Matches: {compliance_matches}
Signals Fired: {json.dumps(signals)}

Return a JSON object with EXACTLY these keys:
- "action": Must be strictly one of: "MONITOR", "ESCALATE", or "BLOCK"
- "reasoning": A 1-2 sentence explanation of why this action was chosen based on the RBI framework.

Return valid JSON only. No extra text.
"""
    try:
        llm = ChatGroq(model="openai/gpt-oss-120b", model_kwargs={"response_format": {"type": "json_object"}}, temperature=0.1, api_key=os.getenv("GROQ_API_KEY"))
        response = llm.invoke([HumanMessage(content=prompt)])
        
        content = response.content
        if isinstance(content, str):
            result = json.loads(content)
        else:
            result = content
            
        action = result.get("action", "MONITOR").upper()
        if action not in ["MONITOR", "ESCALATE", "BLOCK"]:
            action = "ESCALATE" if risk_score > 0.5 else "MONITOR"
            
        return {
            "action": action,
            "confidence": 0.9,
            "reasoning": result.get("reasoning", "Recommendation generated by AI."),
            "thresholds_used": {}
        }
    except Exception as e:
        print("Llama3 Recommender error:", e)
        return {
            "action": "ESCALATE" if risk_score >= 0.5 else "MONITOR",
            "confidence": 0.5,
            "reasoning": "Fallback reasoning due to AI error.",
            "thresholds_used": {}
        }









